### ISSUE TITLE
go-dupfinder deletes the original file

### ISSUE THREAD

**Issue by mesmoiron** [mrinjamul/go-dupfinder#1]
**Describe the bug**

I tested go-dupefinder on Ubuntu and it deletes the original file

**To Reproduce**
1. Copy and paste a document in a folder
2. In terminal go-dupfinder find /path/to/some/directory
3. press y to see duplicates: y
4. go-dupfinder shows me the original file eg file.pdf instead of file(1).pdf
5. delete duplicate: y
6. deletes the original file.pdf file
7. file cannot be found in the trash bin!

**Expected behavior**
A duplicate finder that uses hash and time to figure out what the duplicate is, and if a file has been changed internally.

**Screenshots**

**Desktop (please complete the following information):**
- Ubuntu 22.04
- Konsole

**Comment by mrinjamul** [comment]
Sorry to hear that from you. I know about this. It keeps only one unique file and deletes others but does not think about the filename. It has been 2 years and I lost motivation and the time to work on this project. I developed it because I had thousands of music files on a hard disk and in some directories, there were duplicates. so I decided to clean them up and free up spaces. 

But after some time, I saw that no one was gonna use this project, so I abandoned it. there are a lot of alternatives out there. one of them is [fdupes](https://github.com/adrianlopezroche/fdupes#readme). Also this [list of alternatives](https://askubuntu.com/a/118389).

**Thank you for using this tool. but do have not the time to maintain it anymore.
Again, thanks for using dupfinder. Now consider using other alternatives.**
